### ISSUE TITLE
error during render

### ISSUE THREAD

**Issue by yjcaimeow** [wentaoyuan/pcn#62]
Hi @mihaimorariu @wentaoyuan @kvmanohar22 , 
I meet some error when prepare partial data, just as shown by the following code, do you know what happen?

Blender 2.92.0 (hash 02948a2cab44 built 2021-02-25 09:27:51)
Read prefs: /Users/caiyingjie/Library/Application Support/Blender/2.92/config/userpref.blend
Info: Deleted 1 object(s)
Info: Deleted 1 object(s)
Traceback (most recent call last):
  File "/Users/caiyingjie/Downloads/pcn-master/render/render_depth.py", line 118, in <module>
    bpy.ops.transform.rotate(value=-np.pi / 2, axis=(1, 0, 0))
  File "/Applications/Blender.app/Contents/Resources/2.92/scripts/modules/bpy/ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.transform.rotate.poll() failed, context is incorrect

Best,
yjcai

**Comment by yjcaimeow** [comment]
use blender 2.79 version
