### ISSUE TITLE
@ops.RegisterShape('ApproxMatch') AttributeError: module 'tensorflow.python.framework.ops' has no attribute 'RegisterShape'

### ISSUE THREAD

**Issue by MarioCavero** [wentaoyuan/pcn#67]
The problem itself is quite clear. Regardless the version of TF, Cuda, and the rest, and also in the most updated ones, I keep getting this error. From my understanding, I assume that this error should pop up with updated versions of tensorflow and etc, but I get it in all the tries I have done no matter what. 
I see this can be done [registering the operations via C++](https://www.tensorflow.org/guide/create_op ), with the proper implementation of `SetShapeFn`, but I don't understand how and what parameters to make it. It's strange that I haven't found any implementation to fix this and I am having trouble doing it as well. 
Any ideas? 

```
Traceback (most recent call last):
  File "demo.py", line 121, in <module>
    main()
  File "demo.py", line 77, in main
    model_module = importlib.import_module('.%s' % args.model_type, 'models')
  File "/home/mario/anaconda3/envs/pcnconda/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mario/Downloads/pcn-master/models/pcn_cd.py", line 26, in <module>
    from tf_util import *
  File "/home/mario/Downloads/pcn-master/tf_util.py", line 26, in <module>
    from pc_distance import tf_nndistance, tf_approxmatch
  File "/home/mario/Downloads/pcn-master/pc_distance/tf_approxmatch.py", line 21, in <module>
    @ops.RegisterShape('ApproxMatch')
AttributeError: module 'tensorflow.python.framework.ops' has no attribute 'RegisterShape'
```

**Comment by MarioCavero** [comment]
Taking into account the comments on the functions (Thanks, by the way) like:
```
def approx_match(xyz1,xyz2):
    '''
input:
    xyz1 : batch_size * #dataset_points * 3
    xyz2 : batch_size * #query_points * 3
returns:
    match : batch_size * #query_points * #dataset_points
    '''
    return approxmatch_module.approx_match(xyz1,xyz2)
@ops.RegisterShape('ApproxMatch')
def _approx_match_shape(op):
    shape1=op.inputs[0].get_shape().with_rank(3)
    shape2=op.inputs[1].get_shape().with_rank(3)
    return [tf.TensorShape([shape1.dims[0],shape2.dims[1],shape1.dims[1]])]
```

We can certainly register that operator in c++. Tensorflow has a guide for when updating the project with   ` tf_upgrade_v2 `. I don't recommend it though as this model won't work in the end when upgrading TF version. Specifically use the versions of the author (I still can't manage to get it running due to paths installation problems). The reason for this is that the different versions are not compatible. 

Anyways, for the registration of the operators in c++:
```
#include "tensorflow/core/framework/shape_inference.h"
using namespace tensorflow;
REGISTER_OP("ApproxMatch")
    .Input("xyz1: float32")
    .Input("xyz2: float32")
    .Output("match: float32")
    .SetShapeFn([](shape_inference::InferenceContext* c) {
        shape_inference::ShapeHandle xyz1_shape = c->input(0);
        shape_inference::ShapeHandle xyz2_shape = c->input(1);
        // batch_size is the first dimension 
        shape_inference::DimensionHandle batch_size = c->Dim(xyz1_shape, 0);
        // dataset_points points is the 2nd dimension of the first input
        shape_inference::DimensionHandle dataset_points = c->Dim(xyz1_shape, 1);
        // query_points points is the 2nd dimension of the second input
        shape_inference::DimensionHandle query_points = c->Dim(xyz2_shape, 1);
        // Creating the new shape (batch_size, query_points, dataset_points)
        // and setting it to the output
        c->set_output(0, c->MakeShape({batch_size, query_points, dataset_points})); 
        // Returning a status telling that everything went well
        return Status::OK();    
    });
```
and 
```
REGISTER_OP("MatchCost")
    .Input("xyz1: float32")
    .Input("xyz2: float32")
    .Input("match: float32")
    .Output("cost: float32")
    .SetShapeFn([](shape_inference::InferenceContext* c) {
        shape_inference::DimensionHandle batch_size = c->Dim(c->input(0), 0);
        c->set_output(0, c->Vector(batch_size));
        return Status::OK();        
    });
```
As mentioned by the user that helped me out on SO [see question here](https://stackoverflow.com/questions/72010560/tensorflow-migration-problem-regardless-defining-the-operations-tensorflow-pytho/72129084#72129084), This code does not contain any error handling (for example, checking that the first dimensions of the 2 inputs are the same, or that the last dimension of both inputs is 3). I let that as an exercise to the reader, you could look at the aforementioned guide or directly to the [source code of some ops](https://github.com/tensorflow/tensorflow/blob/v2.8.0/tensorflow/core/ops/math_ops.cc) to have an idea on how to do error handling, with, for example, the macro TF_RETURN_IF_ERROR.


After fixing this, the following error will pop up, meaning that CUDA versions, TF versions are incompatible. 

```
Traceback (most recent call last):
  File "lmdb_writer.py", line 35, in <module>
    from tensorpack import DataFlow, dataflow
  File "/home/mario/.local/lib/python3.6/site-packages/tensorpack/_init_.py", line 5, in <module>
    from tensorpack.libinfo import _version_, _HAS_TF
  File "/home/mario/.local/lib/python3.6/site-packages/tensorpack/libinfo.py", line 47, in <module>
    import tensorflow as tf  # noqa
  File "/home/mario/.local/lib/python3.6/site-packages/tensorflow/_init_.py", line 438, in <module>
    _ll.load_library(_main_dir)
  File "/home/mario/.local/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 154, in load_library
    py_tf.TF_LoadLibrary(lib)
tensorflow.python.framework.errors_impl.NotFoundError: /home/mario/anaconda3/envs/pcnconda/lib/python3.6/site-packages/tensorflow/core/kernels/libtfkernel_sobol_op.so: undefined symbol: _ZN10tensorflow8OpKernel11TraceStringB5cxx11EPNS_15OpKernelContextEb
```
