### ISSUE TITLE
render_depth.py doesn't save exr files

### ISSUE THREAD

**Issue by matthiasjaeger95** [wentaoyuan/pcn#69]
When I execute the render_depth.py file it doesn't save any EXR files. I can see the depth images in the buffer while the code is running it just doesn't save the OpenEXR files into the folder. 

The folders for exr and for every file is created but they are just empty. 

**Here is my Blender. log if i keep it running until the end:** 

Progress:   0.00%
(  0.0000 sec |   0.0000 sec) Importing OBJ '/home/matthias/Blender/render/dataset_train/01234567/0706.obj'...
Progress:   0.00%
  (  0.0001 sec |   0.0000 sec) Parsing OBJ file...
Progress:   0.00%
    (  0.2095 sec |   0.2094 sec) Done, loading materials and images...
Progress:  33.33%
    (  0.2098 sec |   0.2098 sec) Done, building geometries (verts:30375 faces:10278 materials: 1 smoothgroups:0) ...
Progress:  66.67%
    (  0.3019 sec |   0.3018 sec) Done.
Progress:  66.67%
Progress: 100.00%
  (  0.3020 sec |   0.3020 sec) Finished importing: '/home/matthias/Blender/render/dataset_train/01234567/0706.obj'
Progress: 100.00%
Progress: 100.00%

test
Saved: 'buffer.png'
 Time: 00:00.12 (Saving: 00:00.04)

Rendered

[1;31mERROR[0m (bke.lib_id): source/blender/blenkernel/intern/lib_id.c:323 id_us_min: ID user decrement error: MADots Stroke (from '[Main]'): 0 <= 0
[1;31mERROR[0m (bke.lib_id): source/blender/blenkernel/intern/lib_id.c:323 id_us_min: ID user decrement error: MADots Stroke (from '[Main]'): 0 <= 0

**And here is my Blender.log file (after I used Keyboard Interrupt when no EXR files appeared)**

Progress: 0.00%
( 0.0000 sec | 0.0000 sec) Importing OBJ '/home/matthias/Blender/render/dataset_train/01234567/0022.obj'...
Progress: 0.00%
( 0.0001 sec | 0.0000 sec) Parsing OBJ file...
Progress: 0.00%

Error: Python: Traceback (most recent call last):
File "/snap/blender/3082/3.4/scripts/addons/io_scene_obj/init.py", line 133, in execute
return import_obj.load(context, **keywords)
File "/snap/blender/3082/3.4/scripts/addons/io_scene_obj/import_obj.py", line 1010, in load
if len(line_split) == 1 and not context_multi_line and line_start != b'end':
KeyboardInterrupt
Location: /snap/blender/3082/3.4/scripts/modules/bpy/ops.py:113
Error: Python: Traceback (most recent call last):
File "/home/matthias/Blender/render/render_depth.py", line 118, in
bpy.ops.import_scene.obj(filepath=model_path)
File "/snap/blender/3082/3.4/scripts/modules/bpy/ops.py", line 113, in call
ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
File "/snap/blender/3082/3.4/scripts/addons/io_scene_obj/init.py", line 133, in execute
return import_obj.load(context, **keywords)
File "/snap/blender/3082/3.4/scripts/addons/io_scene_obj/import_obj.py", line 1010, in load
if len(line_split) == 1 and not context_multi_line and line_start != b'end':
KeyboardInterrupt
Location: /snap/blender/3082/3.4/scripts/modules/bpy/ops.py:113
Error: File format is not supported in file '/home/matthias/Blender/render/dataset_train'
Error: argument has no '.blend' file extension, not using as new file, exiting! /home/matthias/Blender/render/dataset_train
Saved session recovery to '/tmp/quit.blend'

Blender quit

Could you please help me with that issue? Thank you very much in advance.

**Comment by wizardlf** [comment]
i also have this problem, if you sovle it help me please please

**Comment by WiktorLigeza** [comment]
same, any updates?

**Comment by hmax233** [comment]
@WiktorLigeza @wizardlf Blender 2.79, OpenEXR 1.3.2, and change the open3d function name in process_exr.py, It successes.
